# Generated by Django 5.1.1 on 2024-09-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        ('portafolio', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecetaBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoletaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.PositiveSmallIntegerField()),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portafolio.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.PositiveSmallIntegerField()),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaBoletaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.PositiveSmallIntegerField()),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.receta')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portafolio.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaFacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.PositiveSmallIntegerField()),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.receta')),
            ],
        ),
    ]
