# Generated by Django 5.1.1 on 2024-09-06 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetaboletadetalle',
            name='receta_boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.recetaboleta'),
            preserve_default=False,
        ),
    ]
