# Generated by Django 5.1.1 on 2024-09-08 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_alter_boletadetalle_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletadetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 48, 26, 951296, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 48, 26, 951296, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recetaboletadetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 48, 26, 953411, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recetafacturadetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 48, 26, 954414, tzinfo=datetime.timezone.utc)),
        ),
    ]
