# Generated by Django 5.1.1 on 2024-09-07 12:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_Creacion',
        ),
        migrations.AddField(
            model_name='sesion',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 37, 2, 679901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='portafolio.grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField( max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 37, 2, 679901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 37, 2, 679901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='grupo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='portafolio.grupo'),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='herramienta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='portafolio.herramienta'),
        ),
        migrations.AlterField(
            model_name='herramientausuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 37, 2, 679901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientausuario',
            name='herramienta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_herramienta', to='portafolio.herramienta'),
        ),
        migrations.AlterField(
            model_name='herramientausuario',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_usuario', to='portafolio.usuario'),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 37, 2, 679901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='grupo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_grupo', to='portafolio.grupo'),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='permiso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_permiso', to='portafolio.permiso'),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 37, 2, 679901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='permiso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permiso', to='portafolio.permiso'),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to='portafolio.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='portafolio.cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 37, 2, 679901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='GrupoUsuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 37, 2, 679901, tzinfo=datetime.timezone.utc)),
        ),
    ]
