# Generated by Django 5.1.1 on 2024-09-07 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 7, 10, 252423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 7, 10, 254801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 7, 10, 254801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientausuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 7, 10, 254801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 7, 10, 256250, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 7, 10, 256756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 7, 10, 256756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 7, 10, 254801, tzinfo=datetime.timezone.utc)),
        ),
    ]
