# Generated by Django 5.1.1 on 2024-09-07 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_alter_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramientagrupo',
            name='grupo_id',
        ),
        migrations.RemoveField(
            model_name='permisogrupo',
            name='grupo_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grupo_id',
        ),
        migrations.RemoveField(
            model_name='herramientagrupo',
            name='herramienta_id',
        ),
        migrations.RemoveField(
            model_name='herramientausuario',
            name='herramienta_id',
        ),
        migrations.RemoveField(
            model_name='herramientausuario',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='permisogrupo',
            name='permiso_id',
        ),
        migrations.RemoveField(
            model_name='permisousuario',
            name='permiso_id',
        ),
        migrations.RemoveField(
            model_name='permisousuario',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cliente_id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 15, 38, 45, 690055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='HerramientaGrupo',
        ),
        migrations.DeleteModel(
            name='Herramienta',
        ),
        migrations.DeleteModel(
            name='HerramientaUsuario',
        ),
        migrations.DeleteModel(
            name='PermisoGrupo',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='PermisoUsuario',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
