# Generated by Django 5.1.1 on 2024-09-08 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0012_alter_cliente_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 3, 26, 12, 67963, tzinfo=datetime.timezone.utc)),
        ),
    ]
