# Generated by Django 5.1.1 on 2024-09-07 00:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_usuario_nombre_alter_empresa_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupo_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='login.grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 51, 27, 540884, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 51, 27, 572131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 51, 27, 572131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientausuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 51, 27, 572131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 51, 27, 572131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 51, 27, 572131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 51, 27, 572131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='GrupoUsuario',
        ),
    ]
