# Generated by Django 5.1.1 on 2024-09-07 22:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_usuario_empresa_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisousuario',
            name='permiso_id',
        ),
        migrations.RemoveField(
            model_name='permisousuario',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grupo_id',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 139695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 117208, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 141525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 141525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 139695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('estado', models.SmallIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 141009, tzinfo=datetime.timezone.utc))),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='login.empresa')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_grupo', to='login.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='HerramientaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 141525, tzinfo=datetime.timezone.utc))),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_empleado', to='login.empleado')),
                ('herramienta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_herramienta', to='login.herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 141525, tzinfo=datetime.timezone.utc))),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_empleado', to='login.empleado')),
                ('permiso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_permiso', to='login.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='SesionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 141525, tzinfo=datetime.timezone.utc))),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 141525, tzinfo=datetime.timezone.utc))),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='HerramientaUsuario',
        ),
        migrations.DeleteModel(
            name='PermisoUsuario',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
    ]
