# Generated by Django 5.1.1 on 2024-09-08 14:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_empleado_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesionusuario',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='sesionempleado',
            name='empleado_id',
        ),
        migrations.AddField(
            model_name='sesionempleado',
            name='empleado',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='login.empleado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 391455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 389245, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 389245, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientaempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 393322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 391455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisoempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 393829, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 393829, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sesionempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 393829, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 393829, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 43, 37, 389245, tzinfo=datetime.timezone.utc)),
        ),
    ]
