# Generated by Django 5.1.1 on 2024-09-08 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_rename_usuario_id_sesionusuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientaempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisoempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sesionempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 17, 22, 429320, tzinfo=datetime.timezone.utc)),
        ),
    ]
