# Generated by Django 5.1.1 on 2024-09-08 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_empresa_usuario_alter_empleado_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='grupo_id',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='herramientaempleado',
            old_name='empleado_id',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='herramientaempleado',
            old_name='herramienta_id',
            new_name='herramienta',
        ),
        migrations.RenameField(
            model_name='herramientagrupo',
            old_name='grupo_id',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='herramientagrupo',
            old_name='herramienta_id',
            new_name='herramienta',
        ),
        migrations.RenameField(
            model_name='permisoempleado',
            old_name='empleado_id',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='permisoempleado',
            old_name='permiso_id',
            new_name='permiso',
        ),
        migrations.RenameField(
            model_name='permisogrupo',
            old_name='grupo_id',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='permisogrupo',
            old_name='permiso_id',
            new_name='permiso',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 63107, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 63107, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 60590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientaempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 65142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='herramientagrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 65142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisoempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 65142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 65142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sesionempleado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 65142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 65142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 44, 49, 63107, tzinfo=datetime.timezone.utc)),
        ),
    ]
