# Generated by Django 5.1.1 on 2024-09-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_grupo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='estado',
            field=models.SmallIntegerField(default=1),
        ),
    ]
