# Generated by Django 5.1.1 on 2024-09-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.SmallIntegerField()),
                ('porcentaje', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImpuestoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('impuesto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.impuesto')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.producto')),
            ],
        ),
    ]
