# Generated by Django 5.1.1 on 2024-09-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('metros', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidades', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.almacen')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.producto')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_total', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('almacen_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.almacen')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.producto')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_total', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('almacen_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.almacen')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250, null=True)),
                ('estado', models.SmallIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField()),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='almacen',
            name='sede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.sede'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.unidad'),
        ),
    ]
