# Generated by Django 5.1.1 on 2024-09-07 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_empresa_fecha_creacion_and_more'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='almacen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='logistica.almacen'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alamcenes', to='logistica.producto'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='login.empresa'),
        ),
    ]
