# Generated by Django 5.1.1 on 2024-09-09 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_alter_inventario_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='sede_id',
            new_name='sede',
        ),
        migrations.RenameField(
            model_name='ingresoinventario',
            old_name='almacen_id',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='ingresoinventario',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='almacen_id',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='unidad_id',
            new_name='unidad',
        ),
        migrations.RenameField(
            model_name='salidainventario',
            old_name='almacen_id',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='salidainventario',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='sede',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.AlterField(
            model_name='ingresoinventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sede',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
