# Generated by Django 5.1.1 on 2024-09-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.SmallIntegerField(default=0)),
                ('precio', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('aforo', models.SmallIntegerField()),
                ('ocupada', models.SmallIntegerField(default=0)),
                ('estado', models.SmallIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField()),
                ('sede_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.sede')),
            ],
        ),
        migrations.CreateModel(
            name='MesaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.mesa')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='platoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.plato')),
                ('sede_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('plato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.plato')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('estado', models.SmallIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField()),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empresa')),
            ],
        ),
    ]
