# Generated by Django 5.1.1 on 2024-09-07 20:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0003_alter_inventario_producto_id'),
        ('proveedores', '0006_alter_proveedor_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('subtotal', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoletaCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 9, 7, 20, 30, 51, 604817, tzinfo=datetime.timezone.utc))),
                ('estado', models.PositiveSmallIntegerField()),
                ('boleta_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_boleta', to='compras.boletacompra')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.producto')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('subtotal', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('total', models.IntegerField()),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 9, 7, 20, 30, 51, 605320, tzinfo=datetime.timezone.utc))),
                ('estado', models.PositiveSmallIntegerField()),
                ('factura_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='compras.facturacompra')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.producto')),
            ],
        ),
    ]
