# Generated by Django 5.1.1 on 2024-09-07 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacompradetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 146236, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='facturacompradetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 22, 54, 32, 146750, tzinfo=datetime.timezone.utc)),
        ),
    ]
