# Generated by Django 5.1.1 on 2024-09-08 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_boletacompradetalle_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacompradetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 3, 26, 12, 67963, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='facturacompradetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 3, 26, 12, 67963, tzinfo=datetime.timezone.utc)),
        ),
    ]
