# Generated by Django 5.1.1 on 2024-09-09 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_alter_boletacompradetalle_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacompradetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 17, 11, 57, 478929, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='facturacompradetalle',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 17, 11, 57, 478929, tzinfo=datetime.timezone.utc)),
        ),
    ]
