# Generated by Django 5.1.1 on 2024-09-07 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_tipoproveedor_remove_herramientagrupo_grupo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 16, 19, 31, 159832, tzinfo=datetime.timezone.utc)),
        ),
    ]
